### ISSUE TITLE
IsSpa mode not work properly with AzureBlobStorageProvider

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-storefront-core#340]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Chrome 78.0.3904.87
- Platform version: 2.13.52
- Storefront version: 4.12

### Expected behavior
For SPA going through a direct link works. 
That is, when you try to get a resource that does not exist on the server-side, a response with code 404 should be returned.

### Actual behavior
When I trying to go by client-side direct link, a 500 error occurs.

Exception:

Microsoft.WindowsAzure.Storage.StorageException: The specified blob does not exist.

Stack trace: 

at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.OpenReadAsync(AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken) at VirtoCommerce.Storefront.Domain.AzureBlobContentProvider.OpenReadAsync(String path) in D:\Projects\VirtoCommerce\vc-storefront-core\VirtoCommerce.Storefront\Domain\ContentBlobProviders\AzureBlobContentProvider.cs:line 64 at VirtoCommerce.Storefront.Domain.AzureBlobContentProvider.OpenRead(String path) in D:\Projects\VirtoCommerce\vc-storefront-core\VirtoCommerce.Storefront\Domain\ContentBlobProviders\AzureBlobContentProvider.cs:line 53 at VirtoCommerce.LiquidThemeEngine.ShopifyLiquidThemeEngine.GetAssetStreamAsync(String filePath) in D:\Projects\VirtoCommerce\vc-storefront-core\VirtoCommerce.LiquidThemeEngine\ShopifyLiquidThemeEngine.cs:line 165 at VirtoCommerce.Storefront.Controllers.AssetController.GetThemeAssets(String path) in D:\Projects\VirtoCommerce\vc-storefront-core\VirtoCommerce.Storefront\Controllers\AssetController.cs:line 56 at lambda_method(Closure , Object ) at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult() at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at System.Threading.Tasks.ValueTask1.get_Result()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
at VirtoCommerce.Storefront.Startup.<>c.<<Configure>b__8_3>d.MoveNext() in D:\Projects\VirtoCommerce\vc-storefront-core\VirtoCommerce.Storefront\Startup.cs:line 432
--- End of stack trace from previous location where exception was thrown ---
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
at VirtoCommerce.Storefront.Middleware.ApiErrorHandlingMiddleware.Invoke(HttpContext context) in D:\Projects\VirtoCommerce\vc-storefront-core\VirtoCommerce.Storefront\Middleware\ApiErrorHandlingMiddleware.cs:line 26

### Steps to reproduce
1. Setup AzureBlobStorage as the blob provider.
2. Turn on IsSPA mode for any store. 
3. In the Browser try to go to some resource of this store that does not exist on the server-side.

**Comment by akak1977** [comment]
Released: https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.1.4
